name: validate pr 

on:
  # this workflow runs when prs to the develop branch are opened/ edited with changes in the force-app folder
  pull_request:
    types: [opened, synchronize]
    branches: [develop]
    paths:
     - 'force-app/**'

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    steps:
      - name: 'setup node'
        uses: actions/setup-node@v3
        with: 
          node-version: '14'

      - name: 'install salesforce cli & plugins'
        shell: bash
        run: |
         wget https://developer.salesforce.com/media/salesforce-cli/sf/channels/stable/sf-linux-x64.tar.xz
         mkdir -p ~/cli/sf
         tar xJf sf-linux-x64.tar.xz -C ~/cli/sf --strip-components 1

      - name: 'check sf version'
        run: | 
         ~/cli/sf/bin/sf --version

      - name: 'get sfdx_auth_url secret for repository'
        shell: bash
        run: |
         echo ${{secrets.SFDX_AUTH_URL}} > ./SFDX_AUTH_URL.txt

      - name: 'authenticate to validation org'
        run: |
         ~/cli/sf/bin/sf org login sfdx-url -f ./SFDX_AUTH_URL.txt -s -a SalesforceGitHubActionsPOC

      - name: 'validate deployment'
        run: |
         ~/cli/sf/bin/sf project deploy validate --manifest manifest/package.xml