name: Validate PR

on:
  # this workflow runs when prs to the develop branch are opened/ edited with changes in the force-app folder
  pull_request:
    types: [opened, synchronize]
    branches: [develop]
    paths:
     - 'force-app/**'

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    steps:
      - name: '1) Load repository into VM environment.'
        uses: actions/checkout@v4

      - name: '2) Install Salesforce CLI.'
        shell: bash
        run: |
         wget https://developer.salesforce.com/media/salesforce-cli/sf/channels/stable/sf-linux-x64.tar.xz
         mkdir -p ~/cli/sf
         tar xJf sf-linux-x64.tar.xz -C ~/cli/sf --strip-components 1

      - name: '3) Get SFDX_AUTH_URL secret for repository.'
        shell: bash
        run: |
         echo ${{secrets.SFDX_AUTH_URL}} > SFDX_AUTH_URL.txt

      - name: '4) Authenticate to validation org.'
        run: |
         ~/cli/sf/bin/sf org login sfdx-url -f SFDX_AUTH_URL.txt -s -a SalesforceGitHubActionsPOC      

      - name: '5) Validate deployment.'
        run: |
         ~/cli/sf/bin/sf project deploy validate --manifest manifest/package.xml